# Обучение моделей для кредитного скоринга
Итак, пришло время снова обучить модели для кредитного скоринга. Обучать мы будем две модели
1. Одна будет работать с новыми клиентами банка, о ком еще нет информации в базе данных 
2. Вторая будет работать со старыми клиентами банка, о которых информация в базе данных имеется

Разумеется, первая модель будет хуже второй за счет того, что для первой модели у нас будет меньше данных. Однако мы все равно должны 

Начнем обучение!

Содержание
1. Импорт библиотек
2. Загрузка данных
3. Обучение модели для новых клиентов
    - Предобработка данных
    - Обучение модели
    - Оценка результатов
4. Обучение модели для старых клиентов
    - Предобработка данных
    - Обучение модели
    - Оценка результатов

## 1. Импорт библиотек

In [98]:
import optuna
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report

sns.set_style("darkgrid")

## 2. Загрузка данных

In [99]:
train_data = pd.read_csv("../data/train_dataset.csv", index_col="id")
train_data.head()

,age,education,income,has_car,car_is_foreign,has_work,has_passport,bki_score,requests_count,rejected_applications_count,region_rating,home_address_category,work_address_category,social_network_analysis_score,first_record_age,default
id,,,,,,,,,,,,,,,,
1,27,1,32000,1,1,0,0,-1.917831,0,0,40,2,3,1,4,0
2,26,2,50000,0,0,0,0,-1.153144,2,0,60,2,3,2,1,0
3,35,1,20000,0,0,1,0,-1.732810,0,0,40,1,2,4,3,0
4,35,2,80000,0,0,1,0,-2.552133,2,0,20,2,3,1,3,0
5,24,3,27000,0,0,0,0,-1.914581,1,0,50,2,3,1,2,0

In [100]:
train_features = train_data.drop(["default"], axis=1)
train_targets = train_data["default"]

## 3. Обучение модели для новых клиентов
Информации о новых клиентов нет в базе данных. Если у нас не будет доступов к базам других банков (если новый клиент является клиентом хоть какого-то банка) мы сможем воспользоваться лишь его анкетными данными.

### Предобработка данных

In [101]:
train_features.columns

Index(['age', 'education', 'income', 'has_car', 'car_is_foreign', 'has_work',
       'has_passport', 'bki_score', 'requests_count',
       'rejected_applications_count', 'region_rating', 'home_address_category',
       'work_address_category', 'social_network_analysis_score',
       'first_record_age'],
      dtype='object')

Отберем только те признаки, которые мы можем использовать в анкете

In [102]:
train_features_model_1 = train_features[[
    'age', 
    'education', 
    'income', 
    'has_car', 
    'car_is_foreign', 
    'has_work',
    'has_passport'
]]

train_features_model_1.head()

    age  education  income  has_car  car_is_foreign  has_work  has_passport
id
1    27          1   32000        1               1         0             0
2    26          2   50000        0               0         0             0
3    35          1   20000        0               0         1             0
4    35          2   80000        0               0         1             0
5    24          3   27000        0               0         0             0

In [103]:
train_features_model_1.shape, train_targets.shape

((180816, 7), (180816,))

Это максимальный приемлемый набор характеристик клиента, которые он впринципе может ввести. Признаков немного, а значит конверсия будет на высоте.

Разобьем получившуюся выборку на тренировочную, валидационную и тестовую

In [104]:
from sklearn.model_selection import train_test_split

TEST_SPLIT=.1
VALIDATION_SPLIT=.1

X_train_validation, X_test, y_train_validation, y_test = train_test_split(
    train_features_model_1, 
    train_targets, 
    test_size=TEST_SPLIT,
    random_state=42
)

X_train, X_valid, y_train, y_valid = train_test_split(
    X_train_validation, 
    y_train_validation, 
    test_size=VALIDATION_SPLIT,
    random_state=42
)

X_train.shape, X_valid.shape, X_test.shape, y_train.shape, y_valid.shape, y_test.shape,

((146460, 7), (16274, 7), (18082, 7), (146460,), (16274,), (18082,))

### Обучение модели
В данном сценарии применим модель `CatBoost` (модель бустинга от Яндекса), которая хорошо справляется с категориальными признаками. Для оптимизации модели воспользуемся библиотекой `Optuna`

In [ ]:
from catboost import CatBoostClassifier, Pool
from sklearn.metrics import f1_score

categorical_features = ["education", "has_car", "car_is_foreign", "has_work", "has_passport"] 

train_pool = Pool(X_train, y_train, cat_features=categorical_features)
test_pool = Pool(X_test, y_test, cat_features=categorical_features)
valid_pool = Pool(X_valid, y_valid, cat_features=categorical_features)

def objective(trial):
    params = {
        "iterations": trial.suggest_int("iterations", 200, 1000),
        "depth": trial.suggest_int("depth", 4, 10),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3),
        "l2_leaf_reg": trial.suggest_float("l2_leaf_reg", 1.0, 10.0),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "random_strength": trial.suggest_float("random_strength", 1.0, 10.0),
        "border_count": trial.suggest_int("border_count", 32, 255),
        "eval_metric": "F1",
        "loss_function": "Logloss",
        "verbose": False,
        "class_weights": [1, sum(y_train==0)/sum(y_train==1)]  # баланс классов
    }

    model = CatBoostClassifier(**params)
    model.fit(train_pool, eval_set=valid_pool, early_stopping_rounds=50)

    preds = model.predict(X_valid)
    return f1_score(y_valid, preds)

# Запуск Optuna
study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=50)

print("Лучшие параметры:", study.best_params)

# Финальная модель
best_model = CatBoostClassifier(**study.best_params)
best_model.fit(train_pool, eval_set=valid_pool)

[I 2025-12-17 20:14:59,214] A new study created in memory with name: no-name-c88c1228-94ba-4e03-9cc3-9a53a9f29f85
[I 2025-12-17 20:15:06,396] Trial 0 finished with value: 0.24496277915632755 and parameters: {'iterations': 527, 'depth': 8, 'learning_rate': 0.20313405062957635, 'l2_leaf_reg': 4.769141332746766, 'subsample': 0.537161217375759, 'random_strength': 2.797793399811127, 'border_count': 229}. Best is trial 0 with value: 0.24496277915632755.
[I 2025-12-17 20:15:08,827] Trial 1 finished with value: 0.2362076011442583 and parameters: {'iterations': 789, 'depth': 4, 'learning_rate': 0.027064967984450676, 'l2_leaf_reg': 3.23405565883557, 'subsample': 0.6865742226546598, 'random_strength': 5.091415785393608, 'border_count': 216}. Best is trial 0 with value: 0.24496277915632755.
[I 2025-12-17 20:15:17,829] Trial 2 finished with value: 0.24504827311635313 and parameters: {'iterations': 758, 'depth': 8, 'learning_rate': 0.17842808274472258, 'l2_leaf_reg': 5.78503150255039, 'subsample': 0.5344630441461384, 'random_strength': 7.236756589629106, 'border_count': 123}. Best is trial 2 with value: 0.24504827311635313.
[I 2025-12-17 20:15:21,331] Trial 3 finished with value: 0.2366567828020756 and parameters: {'iterations': 776, 'depth': 7, 'learning_rate': 0.06755591572725445, 'l2_leaf_reg': 8.326072147241618, 'subsample': 0.8176632367837617, 'random_strength': 1.8622818911442698, 'border_count': 106}. Best is trial 2 with value: 0.24504827311635313.
[I 2025-12-17 20:15:27,693] Trial 4 finished with value: 0.24538078013491055 and parameters: {'iterations': 218, 'depth': 8, 'learning_rate': 0.28794833691795646, 'l2_leaf_reg': 8.039535819775036, 'subsample': 0.6712317450949028, 'random_strength': 2.1177743528530977, 'border_count': 177}. Best is trial 4 with value: 0.24538078013491055.
[I 2025-12-17 20:15:34,825] Trial 5 finished with value: 0.24492638280939116 and parameters: {'iterations': 257, 'depth': 8, 'learning_rate': 0.089407248595808, 'l2_leaf_reg': 3.1909147445732486, 'subsample': 0.7528906296371158, 'random_strength': 4.762114004504348, 'border_count': 141}. Best is trial 4 with value: 0.24538078013491055.
[I 2025-12-17 20:15:43,744] Trial 6 finished with value: 0.24692849949647533 and parameters: {'iterations': 253, 'depth': 10, 'learning_rate': 0.2555610223196599, 'l2_leaf_reg': 3.1384481120124246, 'subsample': 0.5069079604021403, 'random_strength': 5.0110583841858345, 'border_count': 69}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:15:50,399] Trial 7 finished with value: 0.2448244824482448 and parameters: {'iterations': 716, 'depth': 7, 'learning_rate': 0.17704110317058547, 'l2_leaf_reg': 3.025978681359178, 'subsample': 0.9109773574662878, 'random_strength': 1.4903611328266895, 'border_count': 69}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:15:59,187] Trial 8 finished with value: 0.24538152610441766 and parameters: {'iterations': 380, 'depth': 5, 'learning_rate': 0.025501181098144563, 'l2_leaf_reg': 9.67387890305359, 'subsample': 0.73938108448186, 'random_strength': 9.073584663982285, 'border_count': 236}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:16:09,271] Trial 9 finished with value: 0.24663587065675838 and parameters: {'iterations': 613, 'depth': 9, 'learning_rate': 0.26525038528122685, 'l2_leaf_reg': 9.652560454214186, 'subsample': 0.9594611318000298, 'random_strength': 8.230367427585982, 'border_count': 86}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:16:13,056] Trial 10 finished with value: 0.2389513108614232 and parameters: {'iterations': 953, 'depth': 10, 'learning_rate': 0.23511203259948366, 'l2_leaf_reg': 1.1883900909566254, 'subsample': 0.6043437605938566, 'random_strength': 6.648081840308445, 'border_count': 32}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:16:22,721] Trial 11 finished with value: 0.24464409122322045 and parameters: {'iterations': 508, 'depth': 10, 'learning_rate': 0.29330145294041393, 'l2_leaf_reg': 6.070688723959891, 'subsample': 0.9979698662888336, 'random_strength': 9.945946735020833, 'border_count': 78}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:16:25,998] Trial 12 finished with value: 0.2363933236574746 and parameters: {'iterations': 408, 'depth': 10, 'learning_rate': 0.24397583883620108, 'l2_leaf_reg': 7.133282194443034, 'subsample': 0.9042508137537221, 'random_strength': 7.876034126559864, 'border_count': 54}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:16:35,753] Trial 13 finished with value: 0.24440894568690097 and parameters: {'iterations': 628, 'depth': 9, 'learning_rate': 0.12301694658637596, 'l2_leaf_reg': 4.428746073644161, 'subsample': 0.8533231794075664, 'random_strength': 3.6332930032570405, 'border_count': 89}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:16:39,367] Trial 14 finished with value: 0.23639055831373573 and parameters: {'iterations': 408, 'depth': 9, 'learning_rate': 0.2509614635973605, 'l2_leaf_reg': 9.868516960139331, 'subsample': 0.9923728862418302, 'random_strength': 6.566491505722534, 'border_count': 172}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:16:46,649] Trial 15 finished with value: 0.24521147301895965 and parameters: {'iterations': 918, 'depth': 6, 'learning_rate': 0.22439250567143165, 'l2_leaf_reg': 1.5213088430939123, 'subsample': 0.6312534101350904, 'random_strength': 4.11693862035743, 'border_count': 32}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:16:50,325] Trial 16 finished with value: 0.23638324644975733 and parameters: {'iterations': 634, 'depth': 9, 'learning_rate': 0.27682305247484434, 'l2_leaf_reg': 2.1869183714779763, 'subsample': 0.5060490353225896, 'random_strength': 5.710660263555921, 'border_count': 103}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:16:56,792] Trial 17 finished with value: 0.24316474712068104 and parameters: {'iterations': 322, 'depth': 10, 'learning_rate': 0.14055309495345597, 'l2_leaf_reg': 4.4549455654446435, 'subsample': 0.7710963393545834, 'random_strength': 8.359786591789645, 'border_count': 60}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:17:00,643] Trial 18 finished with value: 0.24437361151357095 and parameters: {'iterations': 494, 'depth': 9, 'learning_rate': 0.26337762200141024, 'l2_leaf_reg': 6.823677657496781, 'subsample': 0.9230641418122, 'random_strength': 6.03223593691919, 'border_count': 133}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:17:06,220] Trial 19 finished with value: 0.24327440430438124 and parameters: {'iterations': 882, 'depth': 6, 'learning_rate': 0.20295736989729532, 'l2_leaf_reg': 8.858185608192615, 'subsample': 0.5804383784499336, 'random_strength': 9.052203175249053, 'border_count': 163}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:17:14,280] Trial 20 finished with value: 0.24530343267433855 and parameters: {'iterations': 668, 'depth': 9, 'learning_rate': 0.22375651067013436, 'l2_leaf_reg': 7.087862599370808, 'subsample': 0.8447033646960569, 'random_strength': 3.6025076878700184, 'border_count': 109}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:17:19,321] Trial 21 finished with value: 0.23818331278257296 and parameters: {'iterations': 350, 'depth': 4, 'learning_rate': 0.01557735749948404, 'l2_leaf_reg': 9.813235353559621, 'subsample': 0.6959918881639056, 'random_strength': 8.931804837034857, 'border_count': 250}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:17:25,753] Trial 22 finished with value: 0.24387340013890266 and parameters: {'iterations': 311, 'depth': 5, 'learning_rate': 0.06434202108005051, 'l2_leaf_reg': 9.157142097156578, 'subsample': 0.7743903208478495, 'random_strength': 9.806866480631973, 'border_count': 198}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:17:36,321] Trial 23 finished with value: 0.2452076677316294 and parameters: {'iterations': 430, 'depth': 5, 'learning_rate': 0.11597524320045181, 'l2_leaf_reg': 7.744823022445233, 'subsample': 0.7153346247287622, 'random_strength': 7.419649194650464, 'border_count': 84}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:17:39,047] Trial 24 finished with value: 0.23636363636363636 and parameters: {'iterations': 561, 'depth': 6, 'learning_rate': 0.17264156917847073, 'l2_leaf_reg': 9.28118192016693, 'subsample': 0.6363635366112682, 'random_strength': 8.435988998729762, 'border_count': 158}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:17:41,974] Trial 25 finished with value: 0.24157039541654926 and parameters: {'iterations': 207, 'depth': 7, 'learning_rate': 0.26867062456238466, 'l2_leaf_reg': 5.347365680531144, 'subsample': 0.9575082440530798, 'random_strength': 9.037099551922166, 'border_count': 194}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:17:46,837] Trial 26 finished with value: 0.2446601941747573 and parameters: {'iterations': 461, 'depth': 5, 'learning_rate': 0.29922936538229616, 'l2_leaf_reg': 8.664904665741817, 'subsample': 0.8123540695877448, 'random_strength': 6.711479982605095, 'border_count': 49}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:17:50,106] Trial 27 finished with value: 0.23743197122036713 and parameters: {'iterations': 278, 'depth': 10, 'learning_rate': 0.03882288098980824, 'l2_leaf_reg': 3.813598803850522, 'subsample': 0.7307485044000045, 'random_strength': 5.097236712837964, 'border_count': 124}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:17:57,021] Trial 28 finished with value: 0.244672454617206 and parameters: {'iterations': 369, 'depth': 4, 'learning_rate': 0.19944828530803294, 'l2_leaf_reg': 7.817996783319593, 'subsample': 0.8767133956952979, 'random_strength': 8.220540875538738, 'border_count': 254}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:18:04,619] Trial 29 finished with value: 0.2465069860279441 and parameters: {'iterations': 571, 'depth': 8, 'learning_rate': 0.1508935702241302, 'l2_leaf_reg': 2.2100148722236423, 'subsample': 0.575034655828513, 'random_strength': 9.309404646150245, 'border_count': 232}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:18:07,602] Trial 30 finished with value: 0.23636363636363636 and parameters: {'iterations': 550, 'depth': 8, 'learning_rate': 0.14846097430300328, 'l2_leaf_reg': 2.3695369768796644, 'subsample': 0.5524846138015462, 'random_strength': 7.617853459868662, 'border_count': 94}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:18:14,505] Trial 31 finished with value: 0.24576777534355707 and parameters: {'iterations': 585, 'depth': 8, 'learning_rate': 0.09534327052080982, 'l2_leaf_reg': 2.116369900909412, 'subsample': 0.5034672394720636, 'random_strength': 9.622127399427248, 'border_count': 234}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:18:20,323] Trial 32 finished with value: 0.24589178356713426 and parameters: {'iterations': 608, 'depth': 8, 'learning_rate': 0.10863422052221682, 'l2_leaf_reg': 2.058005530808799, 'subsample': 0.5105594733718032, 'random_strength': 9.62083258321754, 'border_count': 215}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:18:27,516] Trial 33 finished with value: 0.24443334997503743 and parameters: {'iterations': 700, 'depth': 9, 'learning_rate': 0.12991024309876031, 'l2_leaf_reg': 3.8066552007850394, 'subsample': 0.5499326594448003, 'random_strength': 9.462523164483525, 'border_count': 208}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:18:36,141] Trial 34 finished with value: 0.2461022301164397 and parameters: {'iterations': 806, 'depth': 8, 'learning_rate': 0.15872898853755377, 'l2_leaf_reg': 1.7046338265009373, 'subsample': 0.5816675633977862, 'random_strength': 8.630508338255947, 'border_count': 230}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:18:38,976] Trial 35 finished with value: 0.23539460198155107 and parameters: {'iterations': 834, 'depth': 9, 'learning_rate': 0.16093226522600013, 'l2_leaf_reg': 2.6999528823672776, 'subsample': 0.584515669221264, 'random_strength': 7.018940016594263, 'border_count': 221}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:18:46,253] Trial 36 finished with value: 0.24432388989351014 and parameters: {'iterations': 836, 'depth': 7, 'learning_rate': 0.19256569286429648, 'l2_leaf_reg': 1.5135437887165417, 'subsample': 0.6411710503836061, 'random_strength': 2.7782533893305055, 'border_count': 187}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:18:54,167] Trial 37 finished with value: 0.24629463841639312 and parameters: {'iterations': 729, 'depth': 8, 'learning_rate': 0.2250452890696621, 'l2_leaf_reg': 3.6279287526516226, 'subsample': 0.5704897288666555, 'random_strength': 4.479685952071616, 'border_count': 151}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:18:57,209] Trial 38 finished with value: 0.23618457049060734 and parameters: {'iterations': 740, 'depth': 9, 'learning_rate': 0.21789233509664502, 'l2_leaf_reg': 3.673726224888108, 'subsample': 0.5314374355072156, 'random_strength': 4.824943955607875, 'border_count': 148}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:19:03,821] Trial 39 finished with value: 0.2461477284024257 and parameters: {'iterations': 994, 'depth': 7, 'learning_rate': 0.2558937600539186, 'l2_leaf_reg': 2.8322151538252203, 'subsample': 0.6562072166405314, 'random_strength': 4.235351523689065, 'border_count': 71}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:19:06,737] Trial 40 finished with value: 0.23509369676320271 and parameters: {'iterations': 701, 'depth': 10, 'learning_rate': 0.2795380494106455, 'l2_leaf_reg': 4.943577292351721, 'subsample': 0.609478199151755, 'random_strength': 6.016341497481581, 'border_count': 116}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:19:09,680] Trial 41 finished with value: 0.24422120355018043 and parameters: {'iterations': 669, 'depth': 7, 'learning_rate': 0.2606113897917144, 'l2_leaf_reg': 2.898905914546487, 'subsample': 0.6767298043086838, 'random_strength': 4.366987244769427, 'border_count': 70}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:19:13,728] Trial 42 finished with value: 0.24490198010048272 and parameters: {'iterations': 990, 'depth': 7, 'learning_rate': 0.2507318728845241, 'l2_leaf_reg': 3.3867010460991267, 'subsample': 0.5618639984838317, 'random_strength': 2.9934321919531817, 'border_count': 47}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:19:18,754] Trial 43 finished with value: 0.24463393119670684 and parameters: {'iterations': 776, 'depth': 8, 'learning_rate': 0.23397218584408222, 'l2_leaf_reg': 2.75942573153481, 'subsample': 0.5313602671065062, 'random_strength': 5.279722500683686, 'border_count': 68}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:19:25,559] Trial 44 finished with value: 0.24372619861341666 and parameters: {'iterations': 528, 'depth': 8, 'learning_rate': 0.2859099576440557, 'l2_leaf_reg': 4.227125402196696, 'subsample': 0.6149766115504051, 'random_strength': 4.221765397364463, 'border_count': 97}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:19:29,702] Trial 45 finished with value: 0.24529212940608403 and parameters: {'iterations': 893, 'depth': 8, 'learning_rate': 0.18501230685118858, 'l2_leaf_reg': 5.95156690481697, 'subsample': 0.6591379905953497, 'random_strength': 3.8502333064041556, 'border_count': 82}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:19:36,092] Trial 46 finished with value: 0.2454446961489215 and parameters: {'iterations': 741, 'depth': 7, 'learning_rate': 0.21282143599118716, 'l2_leaf_reg': 3.3669024192535186, 'subsample': 0.5964327361240945, 'random_strength': 4.660406262761076, 'border_count': 42}. Best is trial 6 with value: 0.24692849949647533.
[I 2025-12-17 20:19:42,690] Trial 47 finished with value: 0.24852779718534784 and parameters: {'iterations': 262, 'depth': 10, 'learning_rate': 0.23847463499356475, 'l2_leaf_reg': 2.3296576538288507, 'subsample': 0.5662462970442476, 'random_strength': 3.1979928789374137, 'border_count': 63}. Best is trial 47 with value: 0.24852779718534784.
[I 2025-12-17 20:19:51,896] Trial 48 finished with value: 0.24574520413182488 and parameters: {'iterations': 255, 'depth': 10, 'learning_rate': 0.2397572561476628, 'l2_leaf_reg': 2.449853042837051, 'subsample': 0.560849327961449, 'random_strength': 3.221228917181731, 'border_count': 59}. Best is trial 47 with value: 0.24852779718534784.
[I 2025-12-17 20:19:56,511] Trial 49 finished with value: 0.23570456092579986 and parameters: {'iterations': 237, 'depth': 10, 'learning_rate': 0.27183844144429775, 'l2_leaf_reg': 1.2173917438666715, 'subsample': 0.5227637163611342, 'random_strength': 2.6230840534760005, 'border_count': 133}. Best is trial 47 with value: 0.24852779718534784.

Лучшие параметры: {'iterations': 262, 'depth': 10, 'learning_rate': 0.23847463499356475, 'l2_leaf_reg': 2.3296576538288507, 'subsample': 0.5662462970442476, 'random_strength': 3.1979928789374137, 'border_count': 63}
0:	learn: 0.5325703	test: 0.5339385	best: 0.5339385 (0)	total: 119ms	remaining: 31.2s
1:	learn: 0.4481444	test: 0.4502567	best: 0.4502567 (1)	total: 245ms	remaining: 31.8s
2:	learn: 0.4046383	test: 0.4073607	best: 0.4073607 (2)	total: 354ms	remaining: 30.6s
3:	learn: 0.3797940	test: 0.3827813	best: 0.3827813 (3)	total: 408ms	remaining: 26.3s
4:	learn: 0.3671500	test: 0.3705082	best: 0.3705082 (4)	total: 437ms	remaining: 22.4s
5:	learn: 0.3598573	test: 0.3633264	best: 0.3633264 (5)	total: 480ms	remaining: 20.5s
6:	learn: 0.3556628	test: 0.3595314	best: 0.3595314 (6)	total: 579ms	remaining: 21.1s
7:	learn: 0.3530194	test: 0.3569969	best: 0.3569969 (7)	total: 636ms	remaining: 20.2s
8:	learn: 0.3518859	test: 0.3559670	best: 0.3559670 (8)	total: 673ms	remaining: 18.9s
9:	learn: 0.3508709	test: 0.3550991	best: 0.3550991 (9)	total: 744ms	remaining: 18.8s
10:	learn: 0.3501267	test: 0.3544585	best: 0.3544585 (10)	total: 834ms	remaining: 19s
11:	learn: 0.3498300	test: 0.3541599	best: 0.3541599 (11)	total: 884ms	remaining: 18.4s
12:	learn: 0.3492283	test: 0.3535510	best: 0.3535510 (12)	total: 989ms	remaining: 18.9s
13:	learn: 0.3490691	test: 0.3533777	best: 0.3533777 (13)	total: 1.08s	remaining: 19.1s
14:	learn: 0.3489976	test: 0.3533130	best: 0.3533130 (14)	total: 1.17s	remaining: 19.3s
15:	learn: 0.3485793	test: 0.3531058	best: 0.3531058 (15)	total: 1.28s	remaining: 19.7s
16:	learn: 0.3484792	test: 0.3530316	best: 0.3530316 (16)	total: 1.34s	remaining: 19.3s
17:	learn: 0.3484731	test: 0.3530304	best: 0.3530304 (17)	total: 1.37s	remaining: 18.6s
18:	learn: 0.3484293	test: 0.3530249	best: 0.3530249 (18)	total: 1.4s	remaining: 17.8s
19:	learn: 0.3483900	test: 0.3529980	best: 0.3529980 (19)	total: 1.44s	remaining: 17.5s
20:	learn: 0.3481894	test: 0.3528775	best: 0.3528775 (20)	total: 1.55s	remaining: 17.8s
21:	learn: 0.3481292	test: 0.3528171	best: 0.3528171 (21)	total: 1.61s	remaining: 17.6s
22:	learn: 0.3481197	test: 0.3528043	best: 0.3528043 (22)	total: 1.64s	remaining: 17.1s
23:	learn: 0.3480671	test: 0.3527905	best: 0.3527905 (23)	total: 1.72s	remaining: 17s
24:	learn: 0.3479135	test: 0.3527319	best: 0.3527319 (24)	total: 1.84s	remaining: 17.4s
25:	learn: 0.3479007	test: 0.3527241	best: 0.3527241 (25)	total: 1.89s	remaining: 17.2s
26:	learn: 0.3476737	test: 0.3526787	best: 0.3526787 (26)	total: 2.04s	remaining: 17.7s
27:	learn: 0.3476737	test: 0.3526787	best: 0.3526787 (27)	total: 2.06s	remaining: 17.3s
28:	learn: 0.3474925	test: 0.3527217	best: 0.3526787 (27)	total: 2.21s	remaining: 17.7s
29:	learn: 0.3473551	test: 0.3527518	best: 0.3526787 (27)	total: 2.34s	remaining: 18.1s
30:	learn: 0.3472752	test: 0.3527192	best: 0.3526787 (27)	total: 2.48s	remaining: 18.5s
31:	learn: 0.3472060	test: 0.3527629	best: 0.3526787 (27)	total: 2.62s	remaining: 18.8s
32:	learn: 0.3470592	test: 0.3528714	best: 0.3526787 (27)	total: 2.85s	remaining: 19.7s
33:	learn: 0.3470592	test: 0.3528714	best: 0.3526787 (27)	total: 2.87s	remaining: 19.3s
34:	learn: 0.3469775	test: 0.3528386	best: 0.3526787 (27)	total: 3.04s	remaining: 19.7s
35:	learn: 0.3469756	test: 0.3528382	best: 0.3526787 (27)	total: 3.1s	remaining: 19.5s
36:	learn: 0.3469645	test: 0.3528264	best: 0.3526787 (27)	total: 3.16s	remaining: 19.2s
37:	learn: 0.3469506	test: 0.3528410	best: 0.3526787 (27)	total: 3.23s	remaining: 19.1s
38:	learn: 0.3468839	test: 0.3528140	best: 0.3526787 (27)	total: 3.37s	remaining: 19.3s
39:	learn: 0.3468379	test: 0.3528218	best: 0.3526787 (27)	total: 3.5s	remaining: 19.4s
40:	learn: 0.3468189	test: 0.3528242	best: 0.3526787 (27)	total: 3.59s	remaining: 19.4s
41:	learn: 0.3468150	test: 0.3528111	best: 0.3526787 (27)	total: 3.65s	remaining: 19.1s
42:	learn: 0.3468011	test: 0.3528109	best: 0.3526787 (27)	total: 3.74s	remaining: 19s
43:	learn: 0.3467451	test: 0.3528135	best: 0.3526787 (27)	total: 3.88s	remaining: 19.2s
44:	learn: 0.3467264	test: 0.3528184	best: 0.3526787 (27)	total: 3.95s	remaining: 19.1s
45:	learn: 0.3467254	test: 0.3528143	best: 0.3526787 (27)	total: 4.01s	remaining: 18.8s
46:	learn: 0.3466976	test: 0.3528605	best: 0.3526787 (27)	total: 4.1s	remaining: 18.7s
47:	learn: 0.3466804	test: 0.3528686	best: 0.3526787 (27)	total: 4.16s	remaining: 18.6s
48:	learn: 0.3466801	test: 0.3528685	best: 0.3526787 (27)	total: 4.21s	remaining: 18.3s
49:	learn: 0.3466793	test: 0.3528684	best: 0.3526787 (27)	total: 4.25s	remaining: 18s
50:	learn: 0.3466778	test: 0.3528693	best: 0.3526787 (27)	total: 4.33s	remaining: 17.9s
51:	learn: 0.3466760	test: 0.3528711	best: 0.3526787 (27)	total: 4.38s	remaining: 17.7s
52:	learn: 0.3465653	test: 0.3528841	best: 0.3526787 (27)	total: 4.51s	remaining: 17.8s
53:	learn: 0.3465653	test: 0.3528840	best: 0.3526787 (27)	total: 4.54s	remaining: 17.5s
54:	learn: 0.3465611	test: 0.3528867	best: 0.3526787 (27)	total: 4.57s	remaining: 17.2s
55:	learn: 0.3463080	test: 0.3530195	best: 0.3526787 (27)	total: 4.7s	remaining: 17.3s
56:	learn: 0.3461832	test: 0.3530233	best: 0.3526787 (27)	total: 4.83s	remaining: 17.4s
57:	learn: 0.3459470	test: 0.3530380	best: 0.3526787 (27)	total: 4.95s	remaining: 17.4s
58:	learn: 0.3456902	test: 0.3530468	best: 0.3526787 (27)	total: 5.08s	remaining: 17.5s
59:	learn: 0.3454833	test: 0.3531372	best: 0.3526787 (27)	total: 5.2s	remaining: 17.5s
60:	learn: 0.3454641	test: 0.3531299	best: 0.3526787 (27)	total: 5.28s	remaining: 17.4s
61:	learn: 0.3452891	test: 0.3530602	best: 0.3526787 (27)	total: 5.41s	remaining: 17.4s
62:	learn: 0.3451058	test: 0.3530375	best: 0.3526787 (27)	total: 5.55s	remaining: 17.5s
63:	learn: 0.3449018	test: 0.3530720	best: 0.3526787 (27)	total: 5.69s	remaining: 17.6s
64:	learn: 0.3447013	test: 0.3532421	best: 0.3526787 (27)	total: 5.82s	remaining: 17.6s
65:	learn: 0.3445625	test: 0.3532461	best: 0.3526787 (27)	total: 5.96s	remaining: 17.7s
66:	learn: 0.3443534	test: 0.3533148	best: 0.3526787 (27)	total: 6.09s	remaining: 17.7s
67:	learn: 0.3441320	test: 0.3533826	best: 0.3526787 (27)	total: 6.24s	remaining: 17.8s
68:	learn: 0.3439928	test: 0.3533507	best: 0.3526787 (27)	total: 6.38s	remaining: 17.9s
69:	learn: 0.3438255	test: 0.3533069	best: 0.3526787 (27)	total: 6.55s	remaining: 18s
70:	learn: 0.3435597	test: 0.3533380	best: 0.3526787 (27)	total: 6.71s	remaining: 18.1s
71:	learn: 0.3433905	test: 0.3533992	best: 0.3526787 (27)	total: 6.87s	remaining: 18.1s
72:	learn: 0.3432147	test: 0.3533374	best: 0.3526787 (27)	total: 7.03s	remaining: 18.2s
73:	learn: 0.3430951	test: 0.3534316	best: 0.3526787 (27)	total: 7.17s	remaining: 18.2s
74:	learn: 0.3429950	test: 0.3533846	best: 0.3526787 (27)	total: 7.3s	remaining: 18.2s
75:	learn: 0.3429073	test: 0.3533595	best: 0.3526787 (27)	total: 7.42s	remaining: 18.2s
76:	learn: 0.3428447	test: 0.3534131	best: 0.3526787 (27)	total: 7.55s	remaining: 18.1s
77:	learn: 0.3426175	test: 0.3535085	best: 0.3526787 (27)	total: 7.67s	remaining: 18.1s
78:	learn: 0.3424317	test: 0.3535361	best: 0.3526787 (27)	total: 7.79s	remaining: 18s
79:	learn: 0.3423035	test: 0.3535913	best: 0.3526787 (27)	total: 7.91s	remaining: 18s
80:	learn: 0.3422301	test: 0.3535721	best: 0.3526787 (27)	total: 8.02s	remaining: 17.9s
81:	learn: 0.3421178	test: 0.3535628	best: 0.3526787 (27)	total: 8.14s	remaining: 17.9s
82:	learn: 0.3420007	test: 0.3535658	best: 0.3526787 (27)	total: 8.27s	remaining: 17.8s
83:	learn: 0.3419311	test: 0.3535934	best: 0.3526787 (27)	total: 8.39s	remaining: 17.8s
84:	learn: 0.3418194	test: 0.3535985	best: 0.3526787 (27)	total: 8.52s	remaining: 17.7s
85:	learn: 0.3417184	test: 0.3535941	best: 0.3526787 (27)	total: 8.65s	remaining: 17.7s
86:	learn: 0.3417132	test: 0.3535897	best: 0.3526787 (27)	total: 8.72s	remaining: 17.5s
87:	learn: 0.3416176	test: 0.3536268	best: 0.3526787 (27)	total: 8.85s	remaining: 17.5s
88:	learn: 0.3415278	test: 0.3536813	best: 0.3526787 (27)	total: 8.97s	remaining: 17.4s
89:	learn: 0.3412943	test: 0.3536985	best: 0.3526787 (27)	total: 9.11s	remaining: 17.4s
90:	learn: 0.3411480	test: 0.3537845	best: 0.3526787 (27)	total: 9.24s	remaining: 17.4s
91:	learn: 0.3409230	test: 0.3538316	best: 0.3526787 (27)	total: 9.36s	remaining: 17.3s
92:	learn: 0.3407968	test: 0.3538150	best: 0.3526787 (27)	total: 9.51s	remaining: 17.3s
93:	learn: 0.3407525	test: 0.3538043	best: 0.3526787 (27)	total: 9.65s	remaining: 17.2s
94:	learn: 0.3404877	test: 0.3539750	best: 0.3526787 (27)	total: 9.83s	remaining: 17.3s
95:	learn: 0.3403201	test: 0.3540647	best: 0.3526787 (27)	total: 9.97s	remaining: 17.2s
96:	learn: 0.3402279	test: 0.3541065	best: 0.3526787 (27)	total: 10.1s	remaining: 17.2s
97:	learn: 0.3401662	test: 0.3541123	best: 0.3526787 (27)	total: 10.2s	remaining: 17.1s
98:	learn: 0.3399717	test: 0.3541237	best: 0.3526787 (27)	total: 10.4s	remaining: 17.1s
99:	learn: 0.3398896	test: 0.3540874	best: 0.3526787 (27)	total: 10.5s	remaining: 17s
100:	learn: 0.3398010	test: 0.3540859	best: 0.3526787 (27)	total: 10.6s	remaining: 16.9s
101:	learn: 0.3397248	test: 0.3541222	best: 0.3526787 (27)	total: 10.7s	remaining: 16.8s
102:	learn: 0.3396671	test: 0.3541187	best: 0.3526787 (27)	total: 10.9s	remaining: 16.8s
103:	learn: 0.3395039	test: 0.3541343	best: 0.3526787 (27)	total: 11s	remaining: 16.7s
104:	learn: 0.3393598	test: 0.3541164	best: 0.3526787 (27)	total: 11.1s	remaining: 16.6s
105:	learn: 0.3392321	test: 0.3541719	best: 0.3526787 (27)	total: 11.2s	remaining: 16.6s
106:	learn: 0.3390045	test: 0.3542110	best: 0.3526787 (27)	total: 11.4s	remaining: 16.5s
107:	learn: 0.3389088	test: 0.3542175	best: 0.3526787 (27)	total: 11.5s	remaining: 16.4s
108:	learn: 0.3388199	test: 0.3542496	best: 0.3526787 (27)	total: 11.7s	remaining: 16.4s
109:	learn: 0.3386665	test: 0.3543018	best: 0.3526787 (27)	total: 11.8s	remaining: 16.3s
110:	learn: 0.3385147	test: 0.3543986	best: 0.3526787 (27)	total: 11.9s	remaining: 16.2s
111:	learn: 0.3384496	test: 0.3544105	best: 0.3526787 (27)	total: 12.1s	remaining: 16.2s
112:	learn: 0.3383794	test: 0.3544236	best: 0.3526787 (27)	total: 12.2s	remaining: 16.1s
113:	learn: 0.3383023	test: 0.3544350	best: 0.3526787 (27)	total: 12.3s	remaining: 16s
114:	learn: 0.3381215	test: 0.3544527	best: 0.3526787 (27)	total: 12.5s	remaining: 16s
115:	learn: 0.3380082	test: 0.3545121	best: 0.3526787 (27)	total: 12.6s	remaining: 15.9s
116:	learn: 0.3378209	test: 0.3546391	best: 0.3526787 (27)	total: 12.7s	remaining: 15.8s
117:	learn: 0.3377445	test: 0.3547519	best: 0.3526787 (27)	total: 12.9s	remaining: 15.7s
118:	learn: 0.3376789	test: 0.3547441	best: 0.3526787 (27)	total: 13s	remaining: 15.6s
119:	learn: 0.3375820	test: 0.3547828	best: 0.3526787 (27)	total: 13.2s	remaining: 15.6s
120:	learn: 0.3374498	test: 0.3548695	best: 0.3526787 (27)	total: 13.3s	remaining: 15.5s
121:	learn: 0.3373705	test: 0.3549865	best: 0.3526787 (27)	total: 13.5s	remaining: 15.5s
122:	learn: 0.3372238	test: 0.3550258	best: 0.3526787 (27)	total: 13.7s	remaining: 15.4s
123:	learn: 0.3371051	test: 0.3550292	best: 0.3526787 (27)	total: 13.8s	remaining: 15.4s
124:	learn: 0.3369939	test: 0.3550619	best: 0.3526787 (27)	total: 14s	remaining: 15.3s
125:	learn: 0.3368616	test: 0.3550526	best: 0.3526787 (27)	total: 14.1s	remaining: 15.2s
126:	learn: 0.3368286	test: 0.3550588	best: 0.3526787 (27)	total: 14.3s	remaining: 15.2s
127:	learn: 0.3367146	test: 0.3550469	best: 0.3526787 (27)	total: 14.4s	remaining: 15.1s
128:	learn: 0.3364775	test: 0.3551417	best: 0.3526787 (27)	total: 14.5s	remaining: 15s
129:	learn: 0.3364465	test: 0.3551505	best: 0.3526787 (27)	total: 14.7s	remaining: 14.9s
130:	learn: 0.3363078	test: 0.3551322	best: 0.3526787 (27)	total: 14.8s	remaining: 14.8s
131:	learn: 0.3361109	test: 0.3552108	best: 0.3526787 (27)	total: 15s	remaining: 14.7s
132:	learn: 0.3360139	test: 0.3552802	best: 0.3526787 (27)	total: 15.1s	remaining: 14.7s
133:	learn: 0.3359314	test: 0.3553476	best: 0.3526787 (27)	total: 15.3s	remaining: 14.6s
134:	learn: 0.3358121	test: 0.3554072	best: 0.3526787 (27)	total: 15.4s	remaining: 14.5s
135:	learn: 0.3356302	test: 0.3554179	best: 0.3526787 (27)	total: 15.5s	remaining: 14.4s
136:	learn: 0.3354623	test: 0.3555089	best: 0.3526787 (27)	total: 15.7s	remaining: 14.3s
137:	learn: 0.3353990	test: 0.3555035	best: 0.3526787 (27)	total: 15.8s	remaining: 14.2s
138:	learn: 0.3353124	test: 0.3556282	best: 0.3526787 (27)	total: 15.9s	remaining: 14.1s
139:	learn: 0.3351870	test: 0.3556724	best: 0.3526787 (27)	total: 16s	remaining: 14s
140:	learn: 0.3351041	test: 0.3557678	best: 0.3526787 (27)	total: 16.2s	remaining: 13.9s
141:	learn: 0.3350428	test: 0.3557702	best: 0.3526787 (27)	total: 16.3s	remaining: 13.8s
142:	learn: 0.3349830	test: 0.3558496	best: 0.3526787 (27)	total: 16.4s	remaining: 13.7s
143:	learn: 0.3348815	test: 0.3559153	best: 0.3526787 (27)	total: 16.6s	remaining: 13.6s
144:	learn: 0.3347812	test: 0.3559405	best: 0.3526787 (27)	total: 16.7s	remaining: 13.5s
145:	learn: 0.3347028	test: 0.3558949	best: 0.3526787 (27)	total: 16.8s	remaining: 13.4s
146:	learn: 0.3346212	test: 0.3559170	best: 0.3526787 (27)	total: 17s	remaining: 13.3s
147:	learn: 0.3345580	test: 0.3558979	best: 0.3526787 (27)	total: 17.1s	remaining: 13.2s
148:	learn: 0.3343879	test: 0.3560055	best: 0.3526787 (27)	total: 17.3s	remaining: 13.1s
149:	learn: 0.3343533	test: 0.3560105	best: 0.3526787 (27)	total: 17.4s	remaining: 13s
150:	learn: 0.3343181	test: 0.3559992	best: 0.3526787 (27)	total: 17.5s	remaining: 12.9s
151:	learn: 0.3341773	test: 0.3559955	best: 0.3526787 (27)	total: 17.7s	remaining: 12.8s
152:	learn: 0.3341450	test: 0.3559951	best: 0.3526787 (27)	total: 17.8s	remaining: 12.7s
153:	learn: 0.3339957	test: 0.3560075	best: 0.3526787 (27)	total: 17.9s	remaining: 12.6s
154:	learn: 0.3338895	test: 0.3560151	best: 0.3526787 (27)	total: 18.1s	remaining: 12.5s
155:	learn: 0.3338445	test: 0.3559885	best: 0.3526787 (27)	total: 18.3s	remaining: 12.4s
156:	learn: 0.3338073	test: 0.3559871	best: 0.3526787 (27)	total: 18.4s	remaining: 12.3s
157:	learn: 0.3337446	test: 0.3559877	best: 0.3526787 (27)	total: 18.6s	remaining: 12.2s
158:	learn: 0.3336990	test: 0.3560134	best: 0.3526787 (27)	total: 18.7s	remaining: 12.1s
159:	learn: 0.3336207	test: 0.3560524	best: 0.3526787 (27)	total: 18.9s	remaining: 12s
160:	learn: 0.3333422	test: 0.3561201	best: 0.3526787 (27)	total: 19s	remaining: 11.9s
161:	learn: 0.3332421	test: 0.3560893	best: 0.3526787 (27)	total: 19.2s	remaining: 11.8s
162:	learn: 0.3332127	test: 0.3560927	best: 0.3526787 (27)	total: 19.3s	remaining: 11.7s
163:	learn: 0.3330080	test: 0.3561678	best: 0.3526787 (27)	total: 19.5s	remaining: 11.6s
164:	learn: 0.3328908	test: 0.3562288	best: 0.3526787 (27)	total: 19.6s	remaining: 11.6s
165:	learn: 0.3327716	test: 0.3563212	best: 0.3526787 (27)	total: 19.8s	remaining: 11.4s
166:	learn: 0.3326094	test: 0.3564398	best: 0.3526787 (27)	total: 19.9s	remaining: 11.3s
167:	learn: 0.3325211	test: 0.3565281	best: 0.3526787 (27)	total: 20.1s	remaining: 11.2s
168:	learn: 0.3324786	test: 0.3565731	best: 0.3526787 (27)	total: 20.2s	remaining: 11.1s
169:	learn: 0.3324219	test: 0.3565533	best: 0.3526787 (27)	total: 20.4s	remaining: 11s
170:	learn: 0.3322900	test: 0.3565621	best: 0.3526787 (27)	total: 20.5s	remaining: 10.9s
171:	learn: 0.3321224	test: 0.3567319	best: 0.3526787 (27)	total: 20.7s	remaining: 10.8s
172:	learn: 0.3320781	test: 0.3567986	best: 0.3526787 (27)	total: 20.8s	remaining: 10.7s
173:	learn: 0.3319367	test: 0.3568684	best: 0.3526787 (27)	total: 21s	remaining: 10.6s
174:	learn: 0.3318056	test: 0.3569097	best: 0.3526787 (27)	total: 21.1s	remaining: 10.5s
175:	learn: 0.3317706	test: 0.3569349	best: 0.3526787 (27)	total: 21.3s	remaining: 10.4s
176:	learn: 0.3317237	test: 0.3569814	best: 0.3526787 (27)	total: 21.4s	remaining: 10.3s
177:	learn: 0.3316844	test: 0.3570033	best: 0.3526787 (27)	total: 21.6s	remaining: 10.2s
178:	learn: 0.3316174	test: 0.3570817	best: 0.3526787 (27)	total: 21.7s	remaining: 10.1s
179:	learn: 0.3315482	test: 0.3571331	best: 0.3526787 (27)	total: 21.9s	remaining: 9.96s
180:	learn: 0.3314219	test: 0.3571591	best: 0.3526787 (27)	total: 22s	remaining: 9.85s
181:	learn: 0.3313027	test: 0.3572424	best: 0.3526787 (27)	total: 22.2s	remaining: 9.74s
182:	learn: 0.3311878	test: 0.3573252	best: 0.3526787 (27)	total: 22.3s	remaining: 9.63s
183:	learn: 0.3311658	test: 0.3573372	best: 0.3526787 (27)	total: 22.5s	remaining: 9.53s
184:	learn: 0.3310004	test: 0.3573492	best: 0.3526787 (27)	total: 22.6s	remaining: 9.41s
185:	learn: 0.3308628	test: 0.3573828	best: 0.3526787 (27)	total: 22.8s	remaining: 9.3s
186:	learn: 0.3307888	test: 0.3574538	best: 0.3526787 (27)	total: 22.9s	remaining: 9.18s
187:	learn: 0.3306956	test: 0.3573969	best: 0.3526787 (27)	total: 23s	remaining: 9.06s
188:	learn: 0.3306149	test: 0.3574026	best: 0.3526787 (27)	total: 23.1s	remaining: 8.94s
189:	learn: 0.3304336	test: 0.3574433	best: 0.3526787 (27)	total: 23.3s	remaining: 8.82s
190:	learn: 0.3303199	test: 0.3574142	best: 0.3526787 (27)	total: 23.4s	remaining: 8.7s
191:	learn: 0.3302381	test: 0.3575000	best: 0.3526787 (27)	total: 23.5s	remaining: 8.58s
192:	learn: 0.3302157	test: 0.3575023	best: 0.3526787 (27)	total: 23.7s	remaining: 8.46s
193:	learn: 0.3300886	test: 0.3576194	best: 0.3526787 (27)	total: 23.8s	remaining: 8.34s
194:	learn: 0.3299072	test: 0.3577208	best: 0.3526787 (27)	total: 23.9s	remaining: 8.22s
195:	learn: 0.3297254	test: 0.3578068	best: 0.3526787 (27)	total: 24.1s	remaining: 8.1s
196:	learn: 0.3296679	test: 0.3578008	best: 0.3526787 (27)	total: 24.2s	remaining: 7.98s
197:	learn: 0.3295890	test: 0.3578335	best: 0.3526787 (27)	total: 24.3s	remaining: 7.85s
198:	learn: 0.3294687	test: 0.3578633	best: 0.3526787 (27)	total: 24.4s	remaining: 7.73s
199:	learn: 0.3293506	test: 0.3579042	best: 0.3526787 (27)	total: 24.5s	remaining: 7.61s
200:	learn: 0.3293292	test: 0.3579318	best: 0.3526787 (27)	total: 24.7s	remaining: 7.49s
201:	learn: 0.3292412	test: 0.3579958	best: 0.3526787 (27)	total: 24.8s	remaining: 7.37s
202:	learn: 0.3291123	test: 0.3580101	best: 0.3526787 (27)	total: 24.9s	remaining: 7.25s
203:	learn: 0.3290537	test: 0.3580546	best: 0.3526787 (27)	total: 25.1s	remaining: 7.14s
204:	learn: 0.3289592	test: 0.3581422	best: 0.3526787 (27)	total: 25.3s	remaining: 7.02s
205:	learn: 0.3289118	test: 0.3582234	best: 0.3526787 (27)	total: 25.4s	remaining: 6.9s
206:	learn: 0.3288210	test: 0.3582311	best: 0.3526787 (27)	total: 25.5s	remaining: 6.78s
207:	learn: 0.3286859	test: 0.3582786	best: 0.3526787 (27)	total: 25.7s	remaining: 6.66s
208:	learn: 0.3286092	test: 0.3583222	best: 0.3526787 (27)	total: 25.8s	remaining: 6.55s
209:	learn: 0.3285478	test: 0.3583679	best: 0.3526787 (27)	total: 26s	remaining: 6.43s
210:	learn: 0.3284386	test: 0.3584348	best: 0.3526787 (27)	total: 26.1s	remaining: 6.32s
211:	learn: 0.3283666	test: 0.3584405	best: 0.3526787 (27)	total: 26.3s	remaining: 6.2s
212:	learn: 0.3282632	test: 0.3585425	best: 0.3526787 (27)	total: 26.4s	remaining: 6.08s
213:	learn: 0.3280695	test: 0.3585925	best: 0.3526787 (27)	total: 26.6s	remaining: 5.97s
214:	learn: 0.3279510	test: 0.3586339	best: 0.3526787 (27)	total: 26.8s	remaining: 5.85s
215:	learn: 0.3278831	test: 0.3586135	best: 0.3526787 (27)	total: 26.9s	remaining: 5.73s
216:	learn: 0.3277378	test: 0.3587043	best: 0.3526787 (27)	total: 27.1s	remaining: 5.61s
217:	learn: 0.3275976	test: 0.3587011	best: 0.3526787 (27)	total: 27.2s	remaining: 5.49s
218:	learn: 0.3274645	test: 0.3587507	best: 0.3526787 (27)	total: 27.4s	remaining: 5.38s
219:	learn: 0.3274512	test: 0.3587538	best: 0.3526787 (27)	total: 27.5s	remaining: 5.26s
220:	learn: 0.3273846	test: 0.3588212	best: 0.3526787 (27)	total: 27.7s	remaining: 5.13s
221:	learn: 0.3272321	test: 0.3589469	best: 0.3526787 (27)	total: 27.9s	remaining: 5.02s
222:	learn: 0.3271346	test: 0.3589253	best: 0.3526787 (27)	total: 28s	remaining: 4.89s
223:	learn: 0.3270360	test: 0.3588774	best: 0.3526787 (27)	total: 28.1s	remaining: 4.77s

In [108]:
y_pred = best_model.predict(X_test)
acc = sum(y_pred == y_test) / len(y_pred) * 100
print(f"Модель достигла accuracy равной {acc:.1f}%")

Модель достигла accuracy равной 88.5%